#docker-compose up --build

services:
  ingestor_one:
      build: .
      command: python3 src/truflation/data/pipeline_coupler.py examples/csv_example/my_pipeline_details.py
      volumes:
        - pipeline_details:/data/todo
  ingestor_two:
      build: .
      command: python3 src/truflation/data/pipeline_coupler.py examples/csv_example/my_pipeline_details.py
      volumes:
        - pipeline_details:/data/todo
  ingestor_happy:
      build: .
      command: python3 src/truflation/data/ingestors/happy_ingestor.py
      environment:
        - HAPPY_PATH=/ingestor/tests/happy_test.csv
volumes:
  pipeline_details:
    driver: local
